# -*- coding: utf-8 -*-
"""2026_Taupathy_Migration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZwCrCw2d7bMf2qGdqsgqbwQfLjIBdnN

# Tauopathy and Migration Model for Epilepsy

Representation of the loss of phagocytosis and simulation of region migration leading to the installation of a chronic disease.

## Team:

Letícia Ribeiro - Computational Engineering undergraduate student (UFJF)

Eliana Toscano - Professor at the Pathology Department (UFJF)

Marcelo Lobosco - Professor at the Computer Science Department and Computational Modeling Graduate Program (UFJF)

Barbara Quintela - Professor at the Computer Science Department and Computational Modeling Graduate Program (UFJF)

## Support
FAPEMIG TECBIS 00702-25
"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# Parameters
s_P = 100.0 # proteina production rate
s_Mm = 10.0 # microglia-
s_Mp = 10.0 # microglia+
alpha = 0.5 # microglia conversion from + to -
beta = 0.5 # microglia activation
k1 = 0.01        # microglia- coefficient
k2_piora = 0.03  # microglia+ coefficient
d1 = 0.1 # microglia- natural decay
d2 = 0.1 # microglia+ natural decay
k_transfer_base = 0.05  # transfer rate (propagation speed) from EC to DG
gamma = 1.0 # propagation rate increase from microglia

def propagation(t, y, exossomos=1.0):

    P_EC, P_DG, Mm_EC, Mp_EC, Mm_DG, Mp_DG = y
    ## P_EC protein concentration in EC
    ## P_DG protein concentration in DG
    ## Mm_Ec microglia- concentration in EC
    ## Mp_Ec microglia+ concentration in EC
    ## Mm_DG microglia- no giro dentado
    ## Mp_DG microglia+ no giro dentado

    ## total microglia in EC
    microglia_EC = Mm_EC + Mp_EC

    ## Transfer rate ##
    # if there is a high concentration of microglia in EC
    # and exossomes are active the transfer increases
    k_transfer = k_transfer_base * (1 + gamma * microglia_EC * exossomos)

    ## Protein dynamics
    dP_EC_dt = (
        s_P                         # s_P = constant source
        - k1 * Mm_EC * P_EC         # - k1 * Mm_EC * P_EC = phagocytosis by microglia-
        - k2_piora * Mp_EC * P_EC   # - k2 * Mp_EC * P_EC = phagocytosis by microglia+
        - k_transfer * P_EC         # - k_transfer * P_EC = LOSS of protein by transfer to other region
    )

    dP_DG_dt = (
        s_P                         # s_P = constant source
        - k1 * Mm_DG * P_DG         # - k1 * Mm_EC * P_EC = phagocytosis by microglia-
        - k2_piora * Mp_DG * P_DG   # - k2 * Mp_EC * P_EC = phagocytosis by microglia+
        + k_transfer * P_EC         # + k_transfer * P_EC = GAIN of protein by transfer from other region
    )

    # Microglia dynamics
    dMp_EC_dt = s_Mp + beta * P_EC - alpha * Mp_EC - d2 * Mp_EC
    dMm_EC_dt = alpha * Mp_EC - d1 * Mm_EC

    dMp_DG_dt = s_Mp + beta * P_DG - alpha * Mp_DG - d2 * Mp_DG
    dMm_DG_dt = alpha * Mp_DG - d1 * Mm_DG


    return [
        dP_EC_dt, dP_DG_dt,
        dMm_EC_dt, dMp_EC_dt,
        dMm_DG_dt, dMp_DG_dt
    ]

# SIMULATION
def simulation(y0, t_span=(0, 15), exossomos=1.0):
    t_eval = np.linspace(t_span[0], t_span[1], 300)

    sol = solve_ivp(
        lambda t, y: propagation(t, y, exossomos),
        t_span, y0, t_eval=t_eval
    )
    return sol


if __name__ == "__main__":

    # Initial Conditions: high in EC, low in DG; basal microglia
    y0 = [200, 10, 20, 15, 8, 5]

    sol = simulation(y0)

plt.plot(sol.t,sol.y[0],sol.t,sol.y[1])
plt.legend(['EC','DG'], fontsize=16)
plt.xlabel('Time (years)', fontsize=16)
plt.ylabel('p-Tau concentration', fontsize=16)
plt.show()


fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(sol.t, sol.y[0], label="Protein in EC")
axes[0].set_xlabel("Time (years)", fontsize=16)
axes[0].set_ylabel("p-Tau Concentration in EC", fontsize=16)
axes[0].legend(fontsize=16)
axes[0].tick_params(labelsize=12)
axes[0].grid(True)

axes[1].plot(sol.t, sol.y[1], label="Protein in DG")
axes[1].set_xlabel("Time (years)", fontsize=16)
axes[1].set_ylabel("p-Tau Concentration in DG", fontsize=16)
axes[1].legend(fontsize=16)
axes[1].tick_params(labelsize=12)
axes[1].grid(True)

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 3, figsize=(20, 5))

# EC
axes[0].plot(sol.t, sol.y[2], label="Microglia- (EC)")
axes[0].plot(sol.t, sol.y[3], label="Microglia+ (EC)")
#axes[0].set_title("Microglias no EC — Cenário Piora")
axes[0].legend(fontsize=16)
axes[0].tick_params(labelsize=12)
axes[0].set_ylabel("Microglia concentration", fontsize=16)
axes[0].set_xlabel("Time (years)", fontsize=16)
axes[0].grid(True)

# DG
axes[1].plot(sol.t, sol.y[4], label="Microglia- (DG)")
axes[1].plot(sol.t, sol.y[5], label="Microglia+ (DG)")
#axes[1].set_title("Microglias no DG — Cenário Piora")
axes[1].legend(fontsize=16)
axes[1].tick_params(labelsize=12)
axes[1].set_ylabel("Microglia concentration", fontsize=16)
axes[1].set_xlabel("Time (years)", fontsize=16)
axes[1].grid(True)

# Total
microglia_EC = sol.y[2] + sol.y[3]
microglia_DG = sol.y[4] + sol.y[5]

axes[2].plot(sol.t, microglia_EC, label="Microglia (total) - EC")
axes[2].plot(sol.t, microglia_DG, label="Microglia (total) - DG")
#axes[2].set_title("Microglia total (EC x DG)")
axes[2].set_ylabel("Microglia concentration", fontsize=16)
axes[2].set_xlabel("Time (years)", fontsize=16)
axes[2].legend(fontsize=16)
axes[2].tick_params(labelsize=12)
axes[2].grid(True)

plt.tight_layout()
plt.show()

rem_mm_EC = k1 * sol.y[2] * sol.y[0]
rem_mp_EC = k2_piora * sol.y[3] * sol.y[0]

rem_mm_DG = k1 * sol.y[4] * sol.y[1]
rem_mp_DG = k2_piora * sol.y[5] * sol.y[1]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# EC
axes[0].plot(sol.t, rem_mm_EC, label="Removal by M- in EC")
axes[0].plot(sol.t, rem_mp_EC, label="Removal by M+ in EC")
#axes[0].set_title("EC — Remoção de proteína")
axes[0].set_xlabel("Time (years)", fontsize=16)
axes[0].set_ylabel("Protein removal by phagocytosis", fontsize=16)
axes[0].legend(fontsize=16)
axes[0].tick_params(labelsize=12)
axes[0].grid(True)

# DG
axes[1].plot(sol.t, rem_mm_DG, label="Removal by M- in DG")
axes[1].plot(sol.t, rem_mp_DG, label="Removal by M+ in DG")
#axes[1].set_title("DG — Remoção de proteína")
axes[1].set_xlabel("Time", fontsize=16)
axes[1].set_ylabel("Protein removal by phagocytosis", fontsize=16)
axes[1].legend(fontsize=16)
axes[1].tick_params(labelsize=12)
axes[1].grid(True)

plt.tight_layout()
plt.show()
